apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      creationTimestamp: 
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryine4658.azurecr.io/tripinsights/poi:1.0
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: SQL_USER
          value: sqladminiNe4658
        - name: SQL_PASSWORD
          value: qA0w25Fw9
        - name: SQL_SERVER
          value: sqlserverine4658.database.windows.net
        - name: SQL_DBNAME
          value: mydrivingDB
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  namespace: api
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"

spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: poi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tripviewer-ingress
  namespace: api
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: poi
          servicePort: 80
        path: /(api/poi/*.*)
