apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
spec:
  replicas: 3
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      creationTimestamp: 
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryine4658.azurecr.io/tripinsights/userprofile:1.0
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: SQL_USER
          value: sqladminiNe4658
        - name: SQL_PASSWORD
          value: qA0w25Fw9
        - name: SQL_SERVER
          value: sqlserverine4658.database.windows.net
        - name: SQL_DBNAME
          value: mydrivingDB
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
apiVersion: v1
kind: Service
metadata:
  name: userprofile
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: userprofile